Added guidelines.
infiniteoverflow/PokeDex pull request #3
Opened 2021-12-03 06:48 UTC by SharviE29

License and references are not added yet.

2021-12-03 07:25 UTC, iamAbhishekkumar commented
I think references will be added after we complete the project. :)

2021-12-03 10:23 UTC, SharviE29 commented
> I think references will be added after we complete the project. :)

Ok , so is there anything that has to be added in this or is this okay?

2021-12-03 13:59 UTC, iamAbhishekkumar commented
I think, for contribution guidelines this is fine.

2021-12-03 14:59 UTC, SharviE29 commented
> I think, for contribution guidelines this is fine. Project admin, will soon accept your pr :)

Ok , Thanks!

2021-12-05 02:35 UTC, infiniteoverflow requested changes

2021-12-05 02:35 UTC, infiniteoverflow commented on README.md
> +5. Make the changes in the code
In order to commit the changes, you need to "add" the changes. 
You missed the code `git add <list-of-files-changed>`

And provide a strict warning to add only those folder which have been modified. Avoid using `git add .`

2021-12-05 02:39 UTC, infiniteoverflow commented
@SharviE29 you are not supposed to make a PR without creating an issue, and also before creating an issue always reach out to the admin or mentors.

Feel free to reach out to me on the discord server if you have any queries.

@SharviE29 fix the changes that I have requested, then I will merge this PR

2021-12-05 07:28 UTC, SharviE29 commented
> @SharviE29 you are not supposed to make a PR without creating an issue, and also before creating an issue always reach out to the admin or mentors.
> 
> Feel free to reach out to me on the discord server if you have any queries.
> 
> @SharviE29 fix the changes that I have requested, then I will merge this PR

Actually sir there was already an issue that was created for this, so I didn't create one. But yes, I'll keep this in mind. I'll make the changes right away. Thank you.

2021-12-05 07:28 UTC, closed without merging